---
- name: Setup cloudera director repo key
  apt_key:
    url: http://archive.cloudera.com/director/ubuntu/trusty/amd64/director/archive.key
    state: present
  become: yes
  tags:
    - apt

- name: Setup cloudera director repo
  apt_repository:
    repo: "{{ item }}"
    state: present
  become: yes
  with_items:
    - "deb [arch=amd64] http://archive.cloudera.com/director/ubuntu/trusty/amd64/director trusty-director2 contrib"
    - "deb-src http://archive.cloudera.com/director/ubuntu/trusty/amd64/director trusty-director2 contrib"
  tags:
    - apt

- name: Apt Update
  apt:
    update_cache: yes
  become: yes
  changed_when: no

- name: Apt install required packages
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - build-essential
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - apt-transport-https
    - openjdk-8-jdk
  tags:
    - apt

- name: Apt install cloudera
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - cloudera-director-server
    - cloudera-director-client
  tags:
    - apt
